### ISSUE TITLE
Creating invalid output

### ISSUE THREAD

**Issue by uj** [ROM-Knowledgeware/IPASign#1]
The resulting file cannot be installed on an iPhone.  Even if you create an Ad-Hoc IPA that works, and then use IPASign to resign it with the exact same profile and certificate, the new IPA will no longer install.  I have noticed that the "good" IPA created with a Mac has a line break on each side of the data within the DataNode, while the "bad" IPA created with IPASign does not contain a line break on either side of the data within the DataNode.  I do not know if that is the issue causing the IPASign file to be rejected by the device.

**Comment by ROM-Knowledgeware** [comment]
In the past, IPASign was able to produce an IPA that was identical to the one produced by Apple's codesign. I have successfully installed the resulting IPAs on iPhones in the recent past.
It's possible that with newer versions of iOS / codesign there is some incompatibility, and we can work together to see what changes are needed to make sure that the resulting IPA is identical to the one produced by Apple tools.

**Comment by Xgamefactory** [comment]
will there any updates  ?

**Comment by ROM-Knowledgeware** [comment]
Xgamefactory, can you confirm that there is a problem?
I have recently tested IPASign output IPAs successfully on the latest iOS without any issues.

**Comment by Xgamefactory** [comment]
we get api internal error
is this method works only for distribution or dev too

**Comment by ROM-Knowledgeware** [comment]
Could you provide additional information about the error you are getting:
- Which iOS version are you using
- print-screen of the error screen (and debug information if possible)

The IPA signing process was tested for Ad-Hoc distribution certificates. (both development and production)
