### ISSUE TITLE
unable to package it into a release version

### ISSUE THREAD

**Issue by FZLCCM** [ROM-Knowledgeware/IPASign#10]
I want to package it into a release version, but I can't find this path on my system C:\Program Files (x86)\Microsoft\ILMerge\ilmerge

**Comment by FZLCCM** [comment]
And i want to run this program on a linux system, but he can't find .net framework 4.0, I don't know how to install .net framework 4.0 on Linux.Prompt for the following error：

/usr/share/dotnet/sdk/2.2.300/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/chenzhi/文档/IPASign-master/Utilities/Utilities.csproj]

The build failed. Please fix the build errors and run again.

**Comment by ROM-Knowledgeware** [comment]
1. ILMerge can be downloaded from here: https://www.microsoft.com/en-my/download/details.aspx?id=17630
2. To run the program under Linux you should either use Mono or target the .NET Core.
