### ISSUE TITLE
Cannot run on iOS12 after resigning

### ISSUE THREAD

**Issue by Xinaction** [ROM-Knowledgeware/IPASign#13]
I tested the certificate and profile with the macOS codesign command and it can be installed and run on iOS12.
But after I resigned the same ipa with IPASign, the console prompts the following error when I install it:(Could not extract archive)
I didn't find the problem, thank you for your help.

`-[IXAppInstallCoordinator _clientDelegate_didCancelWithError:client:]: <IXInitiatingAppInstallCoordinator<0x15f178140> identifier:com.maigougou uuid:3B6D38C7-ECE0-4D6C-9717-33B656BC554C creator:App Store>: Got cancel delegate with reason Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedDescription=This app could not be installed at this time., NSLocalizedFailureReason=**Could not extract archive**, NSLocalizedRecoverySuggestion=Could not extract archive, NSUnderlyingError=0x15f0750d0 {Error Domain=MIInstallerErrorDomain Code=5 "Could not extract archive" UserInfo={NSUnderlyingError=0x15f0752e0 {Error Domain=NSPOSIXErrorDomain Code=0 "Undefined error: 0"}, LegacyErrorString=PackageExtractionFailed, FunctionName=+[MIBOMWrapper extractZipArchiveAtURL:toURL:withError:], SourceFileLine=152, NSLocalizedDescription=Could not extract archive}}} client MobileInstallation`

**Comment by Xinaction** [comment]
The difference between the available signature information and the IPASign signature information
Available:

> Format=app bundle with Mach-O universal (armv7 arm64)
> CodeDirectory v=20200 size=16054 flags=0x0(none) hashes=494+5 location=embedded
> Signature size=4696

IPASign:

> Format=app bundle with Mach-O universal (armv7 arm64)
> CodeDirectory v=20200 size=10066 flags=0x0(none) hashes=494+5 location=embedded
> Signature size=4345

**Comment by phpkas** [comment]
Please give me terminal instructions used ♥️

**Comment by ROM-Knowledgeware** [comment]
This is not very helpful without a link to the original IPA,
IPASign uses SharpZipLib for compression so there might be a bug there.

**Comment by Xinaction** [comment]
I compress the ipa into zip to upload, please download and unzip. 
[original ipa.zip]

**Comment by ROM-Knowledgeware** [comment]
Thanks, I'm not sure when I'll have both the time to investigate and access to iOS 12.
in the meantime, you are welcome to investigate this issue on your own:
Try decompressing and re-compressing the resulting IPA and to compare the files in the resulting IPA with the original IPA.

**Comment by gamebtc** [comment]
i fix it.
zip file can't include directory.
fork: https://github.com/gamebtc/IPASign

**Comment by Xinaction** [comment]
> i fix it.
> zip file can't include directory.
> fork: https://github.com/gamebtc/IPASign

Good man!
