### ISSUE TITLE
codesign_allocate: file not in an order that can be processed (code signature data out of place):

### ISSUE THREAD

**Issue by ZanderZhang** [ROM-Knowledgeware/IPASign#15]

**Comment by ROM-Knowledgeware** [comment]
Which steps did you take before encountering this codesign error?
An example IPA would be helpful in order to recreate the issue.

**Comment by ZanderZhang** [comment]
[http://tmp.link/f/5d7711528c1a4](url)

thanks

**Comment by ROM-Knowledgeware** [comment]
Please describe the steps taken before encountering this codesign error.

**Comment by ZanderZhang** [comment]
> Please describe the steps taken before encountering this codesign error.

codesign -f -s "iPhone Distribution: XXX." ExecuteFile

this step causes the error, thanks

**Comment by ROM-Knowledgeware** [comment]
How does this relate to IPASign? please describe all the steps taken.
