### ISSUE TITLE
Sign entire directory

### ISSUE THREAD

**Issue by iambenmitchell** [ROM-Knowledgeware/IPASign#17]
Hello I know you probably don't pay attention to this anymore but is it possible you could make it so that it signs every ipa in a directory? right now I am virtualising linux and that's not very efficient.

My directory looks like this

/dir/appname/appname.ipa

for example

```
/dir/Facebook/Facebook.ipa
/dir/unc0ver/unc0ver.ipa

```
...

I want to be able to sign with a provision file and a .p12 + password, it can output to another directory or better yet just replace the existing ipa

one more thing I should mention is that I have multiple ipas, one for each cert

example:

```
/dir/Facebook/Facebook_cert1.ipa
/dir/Facebook/Facebook_cert2.ipa
```

Here is the script I am using on linux at the moment:

```
cd /root/signedsh/apps
for i in $(find . -name *_Seyed.ipa) ; do
#echo $i
./sign -k "/root/cert/appX.p12" -m "/root/profile/appX.mobileprovision" -p "udidsigning" -z 9 -o "$i" "$i"
done
```

**Comment by ROM-Knowledgeware** [comment]
Sorry, but no.
you're welcome to create a Fork and implement yourself.
