### ISSUE TITLE
how to sign .dylib file ?

### ISSUE THREAD

**Issue by John0King** [ROM-Knowledgeware/IPASign#18]
the .dylib file need to be sign first , in order to  generate new hash in `CodeResource`,  I can see the code in `CodeSignatureHelper.ResignExecutable`  but this method need to use the byes from `CodeResource` , but when sign the `.dylib` we do not have the correct `CodeResource`,  can you help me ?

**Comment by ROM-Knowledgeware** [comment]
I did not and still do not have the time required to add support for framework / dylib files,
Why don't you help me instead and figure this out and create a fork?
