### ISSUE TITLE
Cast Exception 

### ISSUE THREAD

**Issue by bmbmjmdm** [ROM-Knowledgeware/IPASign#3]
I compiled the executable using Microsoft Visual Studio Community 2017, however after selecting my ipa, mobile provisioning profile, certificate, password, and file destination, I get the following error (sorry for the weird bold):

--------------------Exception Text -----------------------
System.InvalidCastException: Unable to cast object of type 'Org.BouncyCastle.Asn1.DerSequence' to type 'Org.BouncyCastle.Asn1.DerInteger'.
   at Org.BouncyCastle.Asn1.Pkcs.Pfx..ctor(Asn1Sequence seq)
   at Org.BouncyCastle.Pkcs.Pkcs12Store.Load(Stream input, Char[] password)
   at IPALibrary.CertificateHelper.GetCertificateAndKeyFromBytes(Byte[] certificateBytes, String password, AsymmetricKeyEntry& privateKey) in C:\Users\Dale\Documents\GitHub\IPASign\IPALibrary\Helpers\CertificateHelper.cs:line 44
   at IPASign.MainForm.ResignIPA(IPAFile ipaFile, Byte[] mobileProvisionBytes, Byte[] signingCertificateBytes, String certificatePassword, String outputIPAPath) in C:\Users\Dale\Documents\GitHub\IPASign\IPASign\MainForm.cs:line 207
   at IPASign.MainForm.btnSaveIPA_Click(Object sender, EventArgs e) in C:\Users\Dale\Documents\GitHub\IPASign\IPASign\MainForm.cs:line 182
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

--------------------- Loaded Assemblies -----------------------
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8935 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
IPASign
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Dale/Documents/GitHub/IPASign/IPASign/bin/Release/IPASign.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8934 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
IPALibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Dale/Documents/GitHub/IPASign/IPASign/bin/Release/IPALibrary.DLL
----------------------------------------
Utilities
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Dale/Documents/GitHub/IPASign/IPASign/bin/Release/Utilities.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.0.518
    Win32 Version: 0.86.0.518
    CodeBase: file:///C:/Users/Dale/Documents/GitHub/IPASign/IPASign/bin/Release/ICSharpCode.SharpZipLib.DLL
----------------------------------------
BouncyCastle
    Assembly Version: 1.8.3.0
    Win32 Version: 1.8.18223.1
    CodeBase: file:///C:/Users/Dale/Documents/GitHub/IPASign/IPASign/bin/Release/BouncyCastle.DLL
----------------------------------------
PListNet
    Assembly Version: 2.0.6533.11465
    Win32 Version: 2.0.2.0
    CodeBase: file:///C:/Users/Dale/Documents/GitHub/IPASign/IPASign/bin/Release/PListNet.DLL
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8931 built by: WinRelRS4
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

**Comment by bmbmjmdm** [comment]
the file selector for certificate allows the user to select a plain certificate, however the program requires they select a certificate contained in a p12 keystore. If the user selects a plain certificate, the above error happens

**Comment by ROM-Knowledgeware** [comment]
Glad you got it figured out,
You are right that the interface is a bit confusing regarding file selection, the reason for this is that a .p12 file is required for signing, but the program also allows to verify an existing signature using  a .cer file.
