### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by Xgamefactory** [ROM-Knowledgeware/IPASign#4]
Hi,
we are using same mobileprovision and p21 certificate as we did signing with codesign on mac
but your tool gives error.

![ipasignerror](https://user-images.githubusercontent.com/22529051/47968564-fbceca00-e07c-11e8-8486-e385f0a3fb76.png)

**Comment by ROM-Knowledgeware** [comment]
Are you using a wildcard signing certificate (e.g. 'com.company.*') ? those are not supported ATM

**Comment by Xgamefactory** [comment]
we dont use wildcard.

**Comment by ROM-Knowledgeware** [comment]
Please send the mobile provision file to my email (tal@kmrom.com) so I could take a closer look, if you could extract the certificate from the .p12 and send it too that would be helpful.

**Comment by TalAloni** [comment]
I believe [this commit](https://github.com/ROM-Knowledgeware/IPASign/commit/3fdfab4622c8045882f92ed2f023e0594612cbcd) solved the issue.

**Comment by ROM-Knowledgeware** [comment]
I believe [this commit](https://github.com/ROM-Knowledgeware/IPASign/commit/3fdfab4622c8045882f92ed2f023e0594612cbcd) solved the issue.
