### ISSUE TITLE
Test IPA without signing certificate

### ISSUE THREAD

**Issue by FailedShack** [ROM-Knowledgeware/IPASign#6]
Would it be possible to test an IPA's signature without providing a personal certificate?
In a similar way that iOS does before letting you install it.

**Comment by ROM-Knowledgeware** [comment]
I was interesting in checking the signature against the issuing certificate and not just the IPA.
'RB App Checker Lite' is a tool that is designed to check just the IPA, and you are welcomed to fork my project and create whatever you need.
