### ISSUE TITLE
Not ReSigning the dynamic libaries which are inside the Frameworks folder

### ISSUE THREAD

**Issue by anshumanchatterji** [ROM-Knowledgeware/IPASign#9]
This should also resign all dylibs inside IPA\Payload\IPA.app\Frameworks folder

**Comment by ROM-Knowledgeware** [comment]
Signing a framework is currently not supported (a pull request is welcomed of course).
I have just pushed an update to master to show an appropriate error message until such support is added.

**Comment by crazyants** [comment]
now,signing a framework is support？
